### ISSUE TITLE
MySQL connection failed: Class Magento\Framework\DB\Logger\FileFactory does not exist

### ISSUE THREAD

**Issue by jupiter01** [interjar/bugsnag-magento2#10]
Magento 2.2.2

Followed the provided install instructions and now the backend and frontend seem to timeout trying to connect to the db.
---
MySQL connection failed: Class Magento\Framework\DB\Logger\FileFactory does not exist · [main] MySQL connection failed: Class Magento\Framework\DB\Logger\FileFactory does not exist

**Comment by josh-carter** [comment]
@jupiter01 Can you try recompiling the DI, looks as though a Factory hasn't been created for some reason:
`bin/magento setup:di:compile`

**Comment by jupiter01** [comment]
It looks like I may have a conflict with another module. I tried a fresh install and no issues arose. I will post further once I figure out what the conflict is.
