### ISSUE TITLE
Could not find package

### ISSUE THREAD

**Issue by CNSam** [interjar/bugsnag-magento2#3]
Hi folks,

Trying to get this installed on Magento 2.1.7 and when running the composer required command im receiving:

"[InvalidArgumentException]                                                                                                                       
  Could not find package interjar/bugsnag at any version for your minimum-stability (alpha). Check the package spelling or your minimum-stability  "

**Comment by josh-carter** [comment]
@CNSam Apologies, it looks like the package on packagist hadn't updated to the new namespace. If you try again now this should be fixed.

**Comment by CNSam** [comment]
Getting closer, im able to pull it down but now when running the module:enable command Im receiving the following error:

```
Unknown module(s): 'Interjar_BugSnag'
root@4e5a5ed210eb:/var/www/html#
```

**Comment by josh-carter** [comment]
@CNSam Sorry again, Module name in `etc/module.xml` was still the old namespace.

**Comment by josh-carter** [comment]
v2.1.1 will fix this
